Support Deno version only 1.31+
For preventing `Deno.command()` errors:

```
error: TypeError: Deno.Command is not a constructor
  const command = new Deno.Command(cmd, {
                  ^
    at run (https://deno.land/x/denops_test@v1.2.0/runner.ts:25:19)
    at withDenops (https://deno.land/x/denops_test@v1.2.0/with.ts:73:16)
    at fn (https://deno.land/x/denops_test@v1.2.0/tester.ts:105:16)
```

This has been introduced at [deno-denops-test@v1.2.0](https://github.com/vim-denops/deno-denops-test/releases/tag/v1.2.0).