Use rhysd/action-setup-Vim due to avoid an unknown error
cf. https://github.com/kg8m/vim-detect-indent/actions/runs/7067114274/job/19240059577

```
/Users/runner/work/_temp/vim/v9.0.1499/bin/vim
dyld[2155]: Library not loaded: '/usr/local/opt/libsodium/lib/libsodium.23.dylib'
  Referenced from: '/Users/runner/work/_temp/vim/v9.0.1499/bin/vim'
  Reason: tried: '/usr/local/opt/libsodium/lib/libsodium.23.dylib' (no such file), '/usr/local/lib/libsodium.23.dylib' (no such file), '/usr/lib/libsodium.23.dylib' (no such file), '/usr/local/Cellar/libsodium/1.0.19/lib/libsodium.23.dylib' (no such file), '/usr/local/lib/libsodium.23.dylib' (no such file), '/usr/lib/libsodium.23.dylib' (no such file)
/Users/runner/work/_temp/c0458fe8-5fa1-4c19-b9bd-ff9b2eec22b8.sh: line 2:  2155 Abort trap: 6           "${DENOPS_TEST_VIM}" --version
Error: Process completed with exit code 134.
```